# Dutch Menu

[[main]]
  identifier = "development"
  name = "MKB Oplossingen"
  url = "/"
  weight = 2

[[main]]
  identifier = "business"
  name = "Enterprise Oplossingen"
  url = "/business/"
  weight = 3

  [[main]]
  identifier = "automations"
  name = "AI-automatisering"
  url = "/automation/"
  weight = 3

[[main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  weight = 4
