# English Menu

[[main]]
  identifier = "home"
  name = "SME Solutions"
  url = "/"
  weight = 2

[[main]]
  identifier = "business"
  name = "Enterprise Solutions"
  url = "/business/"
  weight = 3

  [[main]]
  identifier = "automations"
  name = "AI Automation"
  url = "/automation/"
  weight = 4

[[main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  weight = 5

